### ISSUE TITLE
Extension fails to initialize on Windows while using lix-pm

### ISSUE THREAD

**Issue by mrcdk** [openfl/lime-vscode-extension#100]
The extension fails to initialize on Windows if you are using [`lix-pm`](https://github.com/lix-pm/lix.client) to manage the Haxe and libraries versions. I changed the `lime.executable` setting to `lix run lime` but it continues to spam the following message: `Setting up Lime alias…` 

I've managed to "fix it" by commenting out the following block https://github.com/openfl/lime-vscode-extension/blob/e51e1efc1661f74cb8244dbee45d3d9a77ff7844/src/lime/extension/Main.hx#L690-L717 but I'm don't think that's the correct fix.

**Comment by joshtynjala** [comment]
Yeah, if you're using a custom executable, it shouldn't be trying to find Lime and set up its alias like that. I'll fix it.

**Comment by joshtynjala** [comment]
This should be cleared up when we release the next update.

**Comment by mrcdk** [comment]
Thanks! :smile:
