### ISSUE TITLE
Specifying lime.projectFile breaks code display

### ISSUE THREAD

**Issue by EliteMasterEric** [openfl/lime-vscode-extension#104]
I get an error in the Lime extension output that reads:

```
Error: Command failed: lime display E:\path\to\Project.xml windows -debug -nocolor -Ddisable-version-check --haxelib=hxcpp-debug-server
Error: Incorrect number of arguments for command 'display'
```

It appears the call of the `lime display` command is being formatted incorrectly.

**Comment by joshtynjala** [comment]
Does the actual project.xml file path contain any spaces?

**Comment by EliteMasterEric** [comment]
Ah just checked, the path does contain spaces.

**Comment by joshtynjala** [comment]
Thanks! That should be easy to fix.
