### ISSUE TITLE
this extension breaks vim mode (vscodevim.vim)

### ISSUE THREAD

**Issue by txgruppi** [openfl/lime-vscode-extension#106]
Installing this extension makes `vscodevim.vim` stop working.

I have no experience with VSCode extensions, not sure I can help much.

Is there any way I can help on fixing this?

**Comment by joshtynjala** [comment]
I'm not sure how that's possible. The Lime extension doesn't contribute any keyboard shortcuts at all.

**Comment by txgruppi** [comment]
I understand that. I checked the code here in GH and I can't see anything obvious that would break vimmode, but the only difference between vimmode working and vimmode not working is this extension.

**Comment by txgruppi** [comment]
Just saw this. I'm trying to work on this, but I'm not experienced with VSCode extensions.

![image](https://github.com/openfl/lime-vscode-extension/assets/91159/d8e847cf-b7c6-42c1-838d-10c8e656c600)

Removing `haxe.enableExtendedIndentation` from the project settings fixed it.

**Comment by joshtynjala** [comment]
Ah, interesting. That's a setting provided by the vshaxe extension: https://github.com/vshaxe/vshaxe
