### ISSUE TITLE
status bar items not appearing

### ISSUE THREAD

**Issue by xyrer** [openfl/lime-vscode-extension#17]
status bar items for the current build target, configuration (release, debug or final) as well as an option for additional flags or defines, are not present

**Comment by jgranick** [comment]
This should occur if your workspace has a "project.xml", "project.hxp" or "project.lime" file in the root path, otherwise something may be wrong with the setup.

**Comment by xyrer** [comment]
yes, the project.xml is there, the items don't appear either on vscode or vscode insider after all those instructions. Deleted and did it again to check. no luck.

**Comment by Gama11** [comment]
You need to install vshaxe from source.

**Comment by xyrer** [comment]
I installed vshaxe from git as instructed, I did that from the beginning

**Comment by jgranick** [comment]
Please try the Lime extension and vshaxe extension from the Marketplace, and remove the version you have installed from source. The Lime extension has been released and no longer requires a development version 😁
