### ISSUE TITLE
Environment Setup (Windows)

### ISSUE THREAD

**Issue by thejustinwalsh** [openfl/lime-vscode-extension#22]
Attempting to build with the lime extension on Windows results in:
```
Creating D:/Projects/SiON/Export/windows/obj/obj/msvc-debug-ncxp/__pch/haxe/hxcpp.pch...
'cl.exe' is not recognized as an internal or external command,
operable program or batch file.
Error: Could not create PCH
```

However if I open a command prompt and simply type `lime build windows` within the project root, it launches the compiler just fine.

This issue seems to be isolated to windows (or a particular magic environment of windows), as on mac I can build the macOS target from with VS  Code.

Any ideas?

**Comment by jgranick** [comment]
Have you restarted your computer since installing Visual Studio C++? Sometimes directly after installation, the environment variables are not available until after a restart

**Comment by thejustinwalsh** [comment]
Visual Studio was installed prior to installing the lime by several restart cycles. Typically I sign-out and sign-in after an environment variable change, and it picks it up. I'll check out my windows machine again. If it persists I will fire up the debugger and see what I get.

**Comment by Gama11** [comment]
I can reproduce this. It seems related to https://github.com/openfl/lime-vscode-extension/pull/10 / specifying `env` in `ShellExecutable` options, but I'm not sure why yet.

**Comment by Gama11** [comment]
I no longer have this issue. Not sure what fixed it.
