### ISSUE TITLE
is there a built-in compilation server I can use?

### ISSUE THREAD

**Issue by increpare** [openfl/lime-vscode-extension#26]
Not sure if this is a bug as such, but could't find your contact info - apologies if there is a better place to ask this -_-

1: This extension is great. Thank you.

2: "lime test" is the recommended way to build apps right now right, but I found that by manually running a compilation server with ```haxe --wait -v 6000``` and then adding ```  <haxeflag name="--connect" value="6000"/>``` to my project.xml file things got sped up a lot.  Now, because your plugin is presumably running an auto-complete server already, is there some way to get it to build using this without manually having to run my own server?

**Comment by Gama11** [comment]
It's vshaxe that's running the server: https://github.com/vshaxe/vshaxe/wiki/Configuration#display-port

**Comment by jgranick** [comment]
When there is not a hard-coded value, does VSHaxe still create a compilation server in the background, using an automatically assigned port number?

If there was a way to expose this in the VSHaxe extension interface, we could automatically pass this in when performing OpenFL build commands.

Might also need a "restart server" option, though, if that breaks

**Comment by increpare** [comment]
Ah, your're right, thanks. Here's the corresponding issue on the vshaxe
github page, for reference

https://github.com/vshaxe/vshaxe/issues/79

(guess there's no reason to keep this open? feel free to close...)

2018-03-04 11:47 GMT+01:00 Jens Fischer <notifications@github.com>:

**Comment by Gama11** [comment]
>does VSHaxe still create a compilation server in the background

Yes.

>using an automatically assigned port number?

No, see https://github.com/vshaxe/vshaxe/issues/191.
