### ISSUE TITLE
Do "lime update" automatically

### ISSUE THREAD

**Issue by Gama11** [openfl/lime-vscode-extension#44]
Right now, code completion relies on `lime update` having happened. The Lime extension should do this automatically when necessary, since people keep running into this error that causes the completion cache to fail building:

```
Building Cache...
Type not found : ApplicationMain
Failed - try fixing the error(s) and restarting the language server:

Type not found : ApplicationMain
```

**Comment by jgranick** [comment]
This issue was fixed in latest dev Lime/OpenFL through stronger `display` argument support
