### ISSUE TITLE
Remove Hashlink MacOS debugger catch

### ISSUE THREAD

**Issue by rcstuber** [openfl/lime-vscode-extension#78]
Hi! For a few months Hashlink debugging on MacOS has been integrated. Someone pointed me to a issue with Lime and I found that there still is a legacy OS guard in the code. You can safely remove this block:

https://github.com/haxelime/lime-vscode-extension/blob/c6c3581ae6f556fe56a1bd97827d973e8523d62a/src/lime/extension/Main.hx#L874

Thanks!

**Comment by Gama11** [comment]
>You can safely remove this block:

No you can't, this requires a newer HashLink version, and Lime bundles HashLink (1.10 atm IIRC).

**Comment by rcstuber** [comment]
True, it requires Hashlink v1.12, my assumption was that dependencies are up-to-date always. @Gama11 Merry Christmas ;-)

**Comment by jgranick** [comment]
The blocker is getting new builds, ideally we want a copy of HashLink built using an older macOS version and using an older Linux version (like Ubuntu 16.04). HashLink only has official Windows builds

**Comment by rcstuber** [comment]
Since I don't think official HL Mac/Linux binaries are on the horizon anytime soon, maybe add a from-source compilation step to Lime for Hashlink?
