### ISSUE TITLE
localhost refused to connect on googleChrome

### ISSUE THREAD

**Issue by yooni126** [openfl/lime-vscode-extension#79]
When I want to test a sample project (html5) with vscode(I don't have any issue with flashDevelop) I see this error
**This site can’t be reached
localhost refused to connect.**
 this my lunch.json codes
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}
```
![chrome](https://user-images.githubusercontent.com/3766387/103628987-fd45f680-4f54-11eb-982a-395d4344b240.png)

![flashdevelop](https://user-images.githubusercontent.com/3766387/103628682-9aecf600-4f54-11eb-8e2d-84127b3333d4.png)

**Comment by Gama11** [comment]
You don't need a launch.json, just use the "lime test" build task instead of "lime build".
