### ISSUE TITLE
Lime not recognizing imports, recognizes errors in file.

### ISSUE THREAD

**Issue by tposejank** [openfl/lime-vscode-extension#90]
I cloned a haxeflixel repository, I have 2 now, however when I opened it, it doesn't work. 

"Lime completion setup failed. Is the lime command available? Try running "lime setup" or changing the "lime.executable" setting."

However, in the one that I didn't download, it works fine, and does recognize imports
In the one that doesnt work, errors are still detected, but imports are all subrayed by the red line.

![imagen_2021-11-17_075439](https://user-images.githubusercontent.com/81495861/142204469-4a1e5a95-f31a-454b-be61-e06d8d5cf99e.png)

![imagen_2021-11-17_075503](https://user-images.githubusercontent.com/81495861/142204548-f5443837-0910-4f2d-8337-543b4ae2596f.png)

**Comment by kinoko87** [comment]
Sorry for the super late reply, but it might be because you don't have the correct dependencies installed. Check the Project.xml and download any libraries you haven't before.

You probably already fixed your issues already, but just wanted to say this to prevent future cases of this.
