### ISSUE TITLE
Extension is not using HL_PATH to find HashLink binary

### ISSUE THREAD

**Issue by SeiferTim** [openfl/lime-vscode-extension#92]
using Lime 8.0.0
`lime setup hl` asks where HashLink binary path is.
When you try to debug HashLink in VSCode, it is still looking for it in `C:/HaxeToolkit/haxe/lib/lime/8,0,0/templates/bin/hl/windows/hl.exe`

**Comment by joshtynjala** [comment]
I'm guessing it is probably this code in `Main.resolveHLDebugConfiguration()` that is always using the bundled HL:

```haxe
// TODO: figure out a nicer way to do this
config.hl = Path.join([
    limePath,
    "templates/bin/hl",
    switch (Sys.systemName())
    {
        case "Windows":
            "windows/hl.exe";
        case "Linux":
            "linux/hl";
        case "Mac":
            "mac/hl";
        case other:
            throw 'unsupported OS $other';
    }
]);
```

**Comment by Apprentice-Alchemist** [comment]
And for Lime 8 those paths are wrong anyway.

**Comment by joshtynjala** [comment]
This seems to do the trick:

```haxe
config.hl = Path.join([getProjectDirectory(), outputFile]);
```

This fix will be included in the next version of the Lime VSCode extension.
