### ISSUE TITLE
HL builds don't seem to work with current version (I found out why - fix enclosed)

### ISSUE THREAD

**Issue by gregdenness** [openfl/lime-vscode-extension#94]
Hi,
I just downloaded the latest haxe and lime, got VSCode with the lime, hashlink debugger and haxe extensions, created the lime simpleImage test project and tried running it in VSCode (F5) - and it does nothing with no output.

After spending some time on this problem I looked at the source for the lime vscode extension and it looks like it's not looking in the correct place for hl.exe - Lime 8.0.0 has it in "templates\bin\hl\Windows64" but the extension is looking in "templates\bin\hl\windows".

Like I said, there's no output to tell you this. I fixed it for now by just renaming the folder from windows64 to windows.

Hope this helps.

Thanks,
Greg

**Comment by joshtynjala** [comment]
Fixed in commit 3b0eb7a59c246c2d3e4713a4706dc903558ff873

It will be included in the next update.
