### ISSUE TITLE
Release new stable version ?

### ISSUE THREAD

**Issue by T1mL3arn** [openfl/lime-vscode-extension#96]
Was trying to debug hashlink target and got nothing on stable version of the extension. After some hours I was able to fix the problem by using dev version of the extension. 

**Wat did not work for me:** 

Lime 8.0.0; HashLink 1.12.0; Hashlink debugger 1.3.4; Lime extension 1.4.3

**What works:**

Lime 8.0.0; HashLink 1.12.0; Hashlink debugger 1.3.4; Lime extension a117ef04e715ccae5d267b01c40060922c7733af

**Comment by joshtynjala** [comment]
We're likely to release an update to the VSCode extension when we do some patch releases for Lime and OpenFL early next year.

**Comment by webbedspace** [comment]
Any news on this?

**Comment by joshtynjala** [comment]
I'm hoping to do the release within the next week.

**Comment by joshtynjala** [comment]
Released 1.5.0
