### ISSUE TITLE
Weird Code "Recommendation"

### ISSUE THREAD

**Issue by spacemonkey841** [openfl/lime-vscode-extension#97]
I have seen nothing about this anywhere. For whatever reason, it appears to be showing the name of a parameter before showing the parameter value. Sometimes it is able to be double-clicked to insert itself into the code, other times it's just there in an non-interactable state. This is specifically is tied to the Lime extension as disabling the extension causes this to no longer happen. This is incredibly annoying, how can I get rid of this?

![ex1](https://user-images.githubusercontent.com/77949007/211636045-914e666e-87b3-4ca2-b409-330d133fbf6e.png)
![ex2](https://user-images.githubusercontent.com/77949007/211636052-36188d65-6847-44f5-bf86-920bb6361f55.png)

**Comment by joshtynjala** [comment]
This actually comes from the Haxe extension, and not the Lime extension. It may be disabled using the `haxe.inlayHints` setting.

**Comment by spacemonkey841** [comment]
That worked, thanks!
